import { expect, test } from "@playwright/test";
test("columns and saved views remain isolated across queues and reload", async ({page}) => {
  await page.request.post("http://127.0.0.1:18765/__test__/reset");
  await page.goto("/");
  await page.getByLabel("Server URL").fill("http://127.0.0.1:18765");
  await page.getByRole("button", {name: "Connect", exact: true}).click();
  await page.getByRole("heading", {name: "robotwin", exact: true}).click();
  await page.locator(".column-menu summary").click();
  await page.locator('.column-menu').getByLabel('Priority', {exact:true}).uncheck();
  await page.getByLabel("Custom column · JSON path", {exact: true}).fill("args.foo");
  await page.getByRole("button", {name: "Add", exact: true}).click();
  await page.locator(".column-menu summary").click();
  await page.getByRole("combobox", {name: "Data view"}).click();
  await page.getByRole("button", {name: "+ Create view", exact:true}).click();
  await page.getByLabel("View name").fill("Robot view");
  await page.getByRole("button", {name: "Create view", exact:true}).click();
  await page.goto("/?queue=other");
  await expect(page.locator('th[data-column-id="priority"]')).toBeVisible();
  await expect(page.locator('th[data-column-id="path:args.foo"]')).toHaveCount(0);
  await page.getByRole("combobox", {name:"Data view"}).click();
  await expect(page.getByRole("option", {name:"Robot view"})).toHaveCount(0);
  await page.getByRole("combobox", {name:"Data view"}).press("Escape");
  await page.locator(".column-menu summary").click();
  await page.locator('.column-menu').getByLabel('Routes', {exact:true}).uncheck();
  await page.goto("/?queue=robotwin");
  await expect(page.locator('th[data-column-id="priority"]')).toHaveCount(0);
  await expect(page.locator('th[data-column-id="routes"]')).toBeVisible();
  await expect(page.locator('th[data-column-id="path:args.foo"]')).toBeVisible();
  await expect(page.getByRole("combobox", {name:"Data view"})).toHaveText("Robot view");
  await page.reload();
  await expect(page.locator('th[data-column-id="path:args.foo"]')).toBeVisible();
  await page.goto("/?queue=other");
  await expect(page.locator('th[data-column-id="routes"]')).toHaveCount(0);
  await expect(page.locator('th[data-column-id="priority"]')).toBeVisible();
});
